version: '3'
services:
  # boilerplate:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/home/node/app
  #     - /home/node/code/node_modules
  #   env_file:
  #     - .env
  #   command: develop

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_DATA_DIR: ./data/db
      MONGO_LOG_DIR: ./data/log
      MONGO_INITDB_DATABASE: example
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongodata/data:/data/db
      - ./mongodata/log:/data/log

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
